/ins/sat_status: {
  shape: class
}
/vessel/sensors/ais/position: {
  shape: class
}
/vessel/sensors/depth_sounder: {
  shape: class
}
/vessel/glendinning/propulsion_cmd: {
  shape: class
}
/dev/stub_glendinning/take_control: {
  shape: class
}
/vessel/sensors/satellite_compass/nav_sat_fix: {
  shape: class
}
/unreal/thrusters/stbd_cmd: {
  shape: class
}
/vessel/glendinning/propulsion: {
  shape: class
}
/vessel/mode/arm: {
  shape: class
}
/vessel/control/gearbox/port: {
  shape: class
}
/vessel/control/engine/port: {
  shape: class
}
/vessel/remote_cmd/mode/control: {
  shape: class
}
/robot_description: {
  shape: class
}
/dev/stub_e_disengage/local: {
  shape: class
}
/dev/stub_glendinning/engine/port: {
  shape: class
}
/vessel/remote_cmd/mode/arm: {
  shape: class
}
/tf: {
  shape: class
}
/vessel/perception/tracks: {
  shape: class
}
/vessel/remote_cmd/mode/speed: {
  shape: class
}
/vessel/sensors/helm: {
  shape: class
}
/vessel/derived/within_geofence: {
  shape: class
}
/unreal/thrusters/port_cmd: {
  shape: class
}
/dev/stub_e_disengage/remote: {
  shape: class
}
/vessel/control/helm: {
  shape: class
}
/vessel/perception/objects_with_chip: {
  shape: class
}
/joint_states: {
  shape: class
}
/vessel/glendinning/system_status_cmd: {
  shape: class
}
/vessel/mode/control: {
  shape: class
}
/dev/stub_glendinning/gearbox/port: {
  shape: class
}
/vessel/e_disengage/warning: {
  shape: class
}
/vessel/glendinning/steering: {
  shape: class
}
/dev/stub_glendinning/gearbox/stbd: {
  shape: class
}
/vessel/perception/rois: {
  shape: class
}
/vessel/mode/speed: {
  shape: class
}
/vessel/sensors/ins/imu: {
  shape: class
}
/vessel/remote_cmd/throttle/port: {
  shape: class
}
/vessel/control/engine/stbd: {
  shape: class
}
/vessel/sensors/speed: {
  shape: class
}
/tf_static: {
  shape: class
}
/vessel/glendinning/steering_cmd: {
  shape: class
}
/vessel/perception/objects: {
  shape: class
}
/vessel/sensors/cameras/bow/camera_info_ext: {
  shape: class
}
/vessel/sensors/cameras/bow/image_raw: {
  shape: class
}
/vessel/user/geofence: {
  shape: class
}
/vessel/glendinning/system_status: {
  shape: class
}
/vessel/remote_cmd/throttle/stbd: {
  shape: class
}
/dev/stub_glendinning/helm: {
  shape: class
}
/dev/stub_e_disengage/connection_strength: {
  shape: class
}
/vessel/mode/notification: {
  shape: class
}
/dev/stub_glendinning/engine/stbd: {
  shape: class
}
/vessel/user/waypoints: {
  shape: class
}
/vessel/remote_cmd/helm: {
  shape: class
}
/vessel/e_disengage/triggered: {
  shape: class
}
/groundstation/comms/wifi: {
  shape: class
}
/vessel/control/gearbox/stbd: {
  shape: class
}
/camera_info_bow: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/engine_control_node: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/geofence_manager: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/geolocation: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/object_chipper: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/object_history: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/object_tracker: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/robot_state_publisher: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_ais_publisher: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_e_disengage: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_object_publisher: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_depth_sounder: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_vessel_ins_publisher: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_water_speed_logger: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/waypoint_manager: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/mode_behavior_tree: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/glendinning_control_helm: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/glendinning_control_status: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/stub_glendinning: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/webrtc_video_node: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/ros_api: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/ros_api_params: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/camera_info_bow <- /vessel/sensors/cameras/bow/camera_info_ext
/engine_control_node -> /vessel/mode/control
/engine_control_node -> /vessel/mode/speed
/engine_control_node -> /vessel/remote_cmd/helm
/engine_control_node -> /vessel/remote_cmd/throttle/port
/engine_control_node -> /vessel/remote_cmd/throttle/stbd
/engine_control_node <- /vessel/control/engine/port
/engine_control_node <- /vessel/control/engine/stbd
/engine_control_node <- /vessel/control/gearbox/port
/engine_control_node <- /vessel/control/gearbox/stbd
/engine_control_node <- /vessel/control/helm
/geofence_manager -> /vessel/sensors/satellite_compass/nav_sat_fix
/geofence_manager <- /vessel/derived/within_geofence
/geofence_manager <- /vessel/user/geofence
/geolocation -> /tf
/geolocation -> /tf_static
/geolocation -> /vessel/sensors/cameras/bow/camera_info_ext
/geolocation -> /vessel/sensors/ins/imu
/geolocation -> /vessel/sensors/satellite_compass/nav_sat_fix
/object_chipper -> /vessel/perception/objects
/object_chipper -> /vessel/sensors/cameras/bow/image_raw
/object_chipper <- /vessel/perception/objects_with_chip
/object_history -> /vessel/perception/objects_with_chip
/object_tracker -> /vessel/perception/rois
/object_tracker <- /vessel/perception/objects
/object_tracker <- /vessel/perception/tracks
/robot_state_publisher -> /joint_states
/robot_state_publisher <- /robot_description
/robot_state_publisher <- /tf
/robot_state_publisher <- /tf_static
/stub_ais_publisher <- /vessel/sensors/ais/position
/stub_e_disengage -> /dev/stub_e_disengage/connection_strength
/stub_e_disengage -> /dev/stub_e_disengage/local
/stub_e_disengage -> /dev/stub_e_disengage/remote
/stub_e_disengage <- /vessel/e_disengage/triggered
/stub_e_disengage <- /vessel/e_disengage/warning
/stub_object_publisher -> /vessel/sensors/cameras/bow/image_raw
/stub_object_publisher <- /vessel/perception/objects
/stub_depth_sounder <- /vessel/sensors/depth_sounder
/stub_vessel_ins_publisher <- /ins/sat_status
/stub_vessel_ins_publisher <- /vessel/sensors/ins/imu
/stub_vessel_ins_publisher <- /vessel/sensors/satellite_compass/nav_sat_fix
/stub_water_speed_logger <- /vessel/sensors/speed
/waypoint_manager -> /vessel/sensors/satellite_compass/nav_sat_fix
/waypoint_manager <- /vessel/user/waypoints
/mode_behavior_tree -> /groundstation/comms/wifi
/mode_behavior_tree -> /vessel/derived/within_geofence
/mode_behavior_tree -> /vessel/e_disengage/triggered
/mode_behavior_tree -> /vessel/glendinning/propulsion
/mode_behavior_tree -> /vessel/glendinning/system_status
/mode_behavior_tree -> /vessel/mode/arm
/mode_behavior_tree -> /vessel/mode/control
/mode_behavior_tree -> /vessel/remote_cmd/mode/arm
/mode_behavior_tree -> /vessel/remote_cmd/mode/control
/mode_behavior_tree -> /vessel/remote_cmd/mode/speed
/mode_behavior_tree <- /vessel/mode/arm
/mode_behavior_tree <- /vessel/mode/control
/mode_behavior_tree <- /vessel/mode/notification
/mode_behavior_tree <- /vessel/mode/speed
/glendinning_control_helm -> /vessel/control/helm
/glendinning_control_helm -> /vessel/glendinning/steering
/glendinning_control_helm <- /vessel/glendinning/steering_cmd
/glendinning_control_helm <- /vessel/sensors/helm
/glendinning_control_status -> /vessel/glendinning/system_status
/glendinning_control_status <- /vessel/glendinning/system_status_cmd
/stub_glendinning -> /dev/stub_glendinning/engine/port
/stub_glendinning -> /dev/stub_glendinning/engine/stbd
/stub_glendinning -> /dev/stub_glendinning/gearbox/port
/stub_glendinning -> /dev/stub_glendinning/gearbox/stbd
/stub_glendinning -> /dev/stub_glendinning/helm
/stub_glendinning -> /dev/stub_glendinning/take_control
/stub_glendinning -> /unreal/thrusters/port_cmd
/stub_glendinning -> /unreal/thrusters/stbd_cmd
/stub_glendinning -> /vessel/glendinning/propulsion_cmd
/stub_glendinning -> /vessel/glendinning/steering_cmd
/stub_glendinning -> /vessel/glendinning/system_status_cmd
/stub_glendinning <- /unreal/thrusters/port_cmd
/stub_glendinning <- /unreal/thrusters/stbd_cmd
/stub_glendinning <- /vessel/glendinning/propulsion
/stub_glendinning <- /vessel/glendinning/steering
/stub_glendinning <- /vessel/glendinning/system_status
/webrtc_video_node -> /vessel/sensors/cameras/bow/image_raw