/adder_3/output: {
  shape: class
}
/adder_2/output: {
  shape: class
}
/input_1: {
  shape: class
}
/adder_1/output: {
  shape: class
}
/input_2: {
  shape: class
}
/adder_2: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/adder_3: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/adder_1: {
  style: {
    opacity: 0.6
    3d: true
  }
}
/adder_2 -> /input_1
/adder_2 -> /input_2
/adder_2 <- /adder_2/output
/adder_3 -> /adder_1/output
/adder_3 -> /adder_2/output
/adder_3 <- /adder_3/output
/adder_1 -> /adder_3/output
/adder_1 <- /adder_1/output